USE CARROS;

create TABLE MARCAS (
ID INT NOT NULL auto_increment, 
NOME_MARCAS varchar(50) NOT NULL,
ORIGEM VARCHAR(50) NOT NULL,
PRIMARY KEY (ID)
);
ALTER TABLE MARCAS ADD ORIGEM VARCHAR(50);

CREATE TABLE INVENTARIO (
ID INT NOT NULL AUTO_INCREMENT,
MODELO VARCHAR (110) NOT NULL,
TRANMISSAO VARCHAR (10) NOT NULL,
MOTOR VARCHAR (30) NOT NULL,
COMBUSTIVEL VARCHAR (20) NOT NULL,
MARCAS_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (MARCAS_ID) REFERENCES MARCAS (ID)
);

CREATE TABLE CLIENTES (
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR (50) NOT NULL,
SOBRENOME VARCHAR (50) NOT NULL,
ENDERECO VARCHAR (200) NOT NULL,
PRIMARY KEY (ID)
);

INSERT INTO CLIENTES (NOME , SOBRENOME , ENDERECO)
VALUES ('NATAN' , 'SOBRAL' , ' RUA OURINHOS '),
	('JESSICA', 'SOBRAL','RUA OURINHOS'),
    ('ENZO', 'SOBRAL' , 'RUA OURINHOS'),
    ('NICOLE', 'SOUZA', ' RUA EUA'),
    ('ANDRE' , 'IACOMO', 'RUA 2');
    
   INSERT INTO MARCAS (NOME_DA_MARCA,ORIGEM)
 VALUES 
    ('WW','ALEMANHA'),
    ('GM','EUA'),
    ('FIAT','ITALIA'),
    ('HONDA','JAPAO'),
    ('HYUNDAY','COREIA');
