-- CRIANDO USUARIOS E FILTRANDO DE ONDE ELES PODERAO ACESSAO O BANCO DE DADOS DA EMPRESA 
CREATE USER ANA IDENTIFIED BY '1212';
create user JOAO@LOCALHOST IDENTIFIED BY '1515';
CREATE USER PRISCILA@ANDREIACONO.COM IDENTIFIELD BY '3333';
SELECT * FROM mysql.user   