USE SAKILA;
# ANALISAR DENTRO DO CAMPO QUAL DADO INICIA COM AQUILO QUE ESTOU PEDINDO
# % SIGNIFICA QUALQUER OUTRA COISA APARTIR DO DADO QUE ESTOU SOLICITANDO
SELECT * 
FROM actor
WHERE FIRST_NAME LIKE 'A%';